In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [2]:
house_price_data = {
    'house_sqr_ft': [1200, 1500, 1800, 900, 2000],
    'price': [200000, 250000, 300000, 160000, 330000]
}

df = pd.DataFrame(house_price_data)
df

   house_sqr_ft   price
0          1200  200000
1          1500  250000
2          1800  300000
3           900  160000
4          2000  330000

In [3]:
lr_model = LinearRegression()
lr_model.fit(df[['house_sqr_ft']], df['price'])

LinearRegression()

In [4]:
prediction = lr_model.predict([[1000]])
print(prediction)

[172588.83248731]

d:\Softwares\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [5]:
prediction = lr_model.predict(df[['house_sqr_ft']])
print(prediction)

[204010.15228426 251142.1319797  298274.11167513 156878.17258883
 329695.43147208]

In [6]:
slope = lr_model.coef_[0]
print(slope)

157.10659898477158

In [7]:
intercept = lr_model.intercept_
print(intercept)

15482.23350253806

In [8]:
from sklearn.metrics import r2_score

In [9]:
r2 = r2_score(df[['price']], lr_model.predict(df[['house_sqr_ft']]))
print(r2)

0.9984495356424394

In [10]:
df = pd.read_csv("placement.csv")
df

     cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
lr_model = LinearRegression()

In [13]:
X_train, X_test, y_train, y_test = train_test_split(df['cgpa'], df['package'], test_size=0.2, random_state=40)

In [14]:
X_train = pd.DataFrame(X_train)
X_train

     cgpa
86   7.61
182  5.88
69   7.30
125  7.33
42   5.95
..    ...
50   9.58
184  7.88
165  8.21
7    6.75
70   5.79

[160 rows x 1 columns]

In [15]:
lr_model.fit(X_train, y_train)

LinearRegression()

In [16]:
X_test = pd.DataFrame(X_test)

In [17]:
y_pred = lr_model.predict(X_test)
y_pred

array([3.08765691, 3.54491102, 4.21906771, 2.94696334, 3.18731486,
       3.09938138, 2.94110111, 3.140417  , 3.08765691, 3.18731486,
       3.13455477, 2.98213673, 3.07593245, 3.79112477, 2.68316289,
       3.55663548, 3.6152578 , 2.54833155, 2.34315343, 2.37832682,
       2.50729593, 2.40177575, 1.72761906, 2.90006548, 3.21076379,
       3.00558566, 2.98799896, 2.82385647, 2.73006075, 2.83558093,
       2.64212727, 2.47798477, 3.99044066, 4.37734798, 2.7945453 ,
       3.9611295 , 2.49557147, 2.09693968, 2.73592298, 2.23763325])

In [18]:
X_test = X_test.values.flatten()

In [19]:
X_test.shape

(40,)

In [20]:
y_pred.shape

(40,)

In [21]:
final_df = pd.DataFrame({'cgpa_test': X_test, 'package_pred': y_pred})
final_df

    cgpa_test  package_pred
0        7.11      3.087657
1        7.89      3.544911
2        9.04      4.219068
3        6.87      2.946963
4        7.28      3.187315
5        7.13      3.099381
6        6.86      2.941101
7        7.20      3.140417
8        7.11      3.087657
9        7.28      3.187315
10       7.19      3.134555
11       6.93      2.982137
12       7.09      3.075932
13       8.31      3.791125
14       6.42      2.683163
15       7.91      3.556635
16       8.01      3.615258
17       6.19      2.548332
18       5.84      2.343153
19       5.90      2.378327
20       6.12      2.507296
21       5.94      2.401776
22       4.79      1.727619
23       6.79      2.900065
24       7.32      3.210764
25       6.97      3.005586
26       6.94      2.987999
27       6.66      2.823856
28       6.50      2.730061
29       6.68      2.835581
30       6.35      2.642127
31       6.07      2.477985
32       8.65      3.990441
33       9.31      4.377348
34       6.61      2.794545
35       8.60      3.961129
36       6.10      2.495571
37       5.42      2.096940
38       6.51      2.735923
39       5.66      2.237633

In [22]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [23]:
r2 = r2_score(y_test, y_pred)
print(f"R2 Score: {r2}")

R2 Score: 0.6462843124730799

In [24]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
print(f"MAE: {mae} LPA")
print(f"MSE: {mse}")
print(f"RMSE: {mse ** 0.5} LPA")

MAE: 0.24999051829818955 LPA
MSE: 0.10351480752583128
RMSE: 0.32173717150157094 LPA

In [ ]:
n = X_train.shape[0]
p = 1

In [26]:
adj_r2 = 1 - (((1 - r2) * (n - 1)) / (n-p-1))

print(f"Adj R2 Score: {adj_r2}")

Adj R2 Score: 0.6440456055899981